services:
  component_container:
    build: 
      context: sandbox_components/
    network_mode: "host"
    ipc: "host"
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - ROS_DOMAIN_ID=42

  sandbox_operator:
    build:
      context: sandbox_operator/
    network_mode: "host"
    ipc: "host"
    privileged: true
    environment:
      - ROS_DOMAIN_ID=42
    volumes:
      - /dev:/dev
      - ./config.json:/config/sandbox.json:ro
    depends_on:
      - component_container
    command: >
      ros2 run sandbox_operator operator 
      --ros-args -p role:=all -p is_controller:=true -p config_file_path:=/config/sandbox.json
